### ISSUE TITLE
Multi module Maven support

### ISSUE THREAD

**Issue by jitpack** [jitpack/jitpack.io#1]

**Comment by jitpack** [comment]
Available now

**Comment by dwijnand** [comment]
I was wondering how, and the detail is in https://github.com/jitpack/jitpack.io/blob/9d89bf394f32ad9343ff0e0f503ddeba2a15f994/BUILDING.md#multi-module-projects

**Comment by jitpack** [comment]
@dwijnand Good point!:) Thanks

**Comment by kag0** [comment]
For any like me who stumble on this later, the up to date wiki on how to use multiple modules is here https://github.com/jitpack/jitpack.io/blob/master/BUILDING.md#multi-module-projects  
The significant change is that the builds now use `com.github.User.Repo` as group Id and `ModuleName` as the artifact Id instead of `Repo.ModuleName` as the artifact id.
