### ISSUE TITLE
react-native/0.39.0-AndroidSupportLibrary25.0.1-v0.23.0-rc-gd3913be-3110 build

### ISSUE THREAD

**Issue by jpshelley** [jitpack/jitpack.io#1002]
Log https://jitpack.io/com/github/jpshelley/react-native/0.39.0-AndroidSupportLibrary25.0.1-v0.23.0-rc-gd3913be-3110/build.log

I want to only build the `ReactAndroid` module, not all of the examples with their android applications. Is there a way to do this with the jitpack.yml?

https://github.com/jpshelley/react-native/tree/0.39.0-AndroidSupportLibrary25.0.1/ReactAndroid

**Comment by jitpack-io** [comment]
Hi @jpshelley 

It is possible to only build one module by adding this line to module's build.gradle:
`apply plugin: 'com.github.dcendents.android-maven' `

All the modules with that plugin will be built. In order to use this plugin you need to include it in your root level build.gradle https://jitpack.io/docs/ANDROID/#gradle

For example:
https://github.com/jitpack/android-example

**Comment by jpshelley** [comment]
@jitpack-io How long does it take for the commit to build? Is there any way to see the progress?
