### ISSUE TITLE
Project name with dots - download unauthorized

### ISSUE THREAD

**Issue by mnlipp** [jitpack/jitpack.io#1145]
https://jitpack.io/com/github/mnlipp/org.jdrupes.mdoclet/0.1.0/build.log

The build looks okay, when I try to use it e.g. https://jitpack.io/com/github/mnlipp/org/jdrupes/mdoclet/mdoclet-doclet/0.1.0/mdoclet-doclet-0.1.0.pom I get "401 Unauthorized".

**Comment by mnlipp** [comment]
Okay, got it. Projects with multiple artifacts cannot be used if they are in git repositories with dots in their name. Should be mentioned somewhere, however...

**Comment by chetbox** [comment]
Is there a workaround for this?

**Comment by jitpack-io** [comment]
@chetbox Replacing the dots with `~` in project name should work.

https://jitpack.io/com/github/mnlipp/org~jdrupes~mdoclet/0.1.0/build.log

**Comment by JcMinarro** [comment]
It works with `~` 
But the jigpack web is showing the dependency with dots, then if you copy from them doesn't work.
Could you fix it on the web to show the proper dependency?

**Comment by jcornaz** [comment]
@jitpack-io Using `~`only works with gradle. Maven doesn't accept such character for groupId and the build will fail.
Example:
```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.groupId' for com.github.Kotlin.kotlinx~coroutines:kotlinx-coroutines-core:jar with value 'com.github.Kotlin.kotlinx~coroutines' does not match a valid id pattern.
```

And examples given on the website [jitpack.io](https://jitpack.io/#Kotlin/kotlinx.coroutines/9faa61eeabbc2c111431fb25aa8947363d842d3e) should be corrected too.

**Comment by jcornaz** [comment]
Maven expect an id matching the regex: `[A-Za-z0-9_\\-.]+`

Source: https://github.com/apache/maven/blob/master/maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java#L76

**Comment by aldobongio** [comment]
A FAQ or note about repositories with dots would be really appreciated.

The problem can be spotted building https://github.com/eclipse/paho.mqtt.java
At the end of the [build log](https://jitpack.io/com/github/eclipse/paho.mqtt.java/1.2.1/build.log) you can see wrong paths (`paho/mqtt/java`):
`Files:`
`com/github/eclipse/paho/mqtt/java/org.eclipse.paho.client.mqttv3.test/1.2.1`
`...`
If you try to reference the main module or one of the submodules it fails to build and signals 401 Unauthorized.

If you fork the repository and **rename it with hyphen instead of dots** like https://github.com/aldobongio/paho-mqtt-java the [build log](https://jitpack.io/com/github/aldobongio/paho-mqtt-java/1.2.1/build.log) contains correct paths:
`Files:`
`com/github/aldobongio/paho-mqtt-java/org.eclipse.paho.client.mqttv3.test/1.2.1`
`...`
You can then reference it in your project and it correctly builds.
