### ISSUE TITLE
Build issue: https://github.com/loeschg/android-image-cropper

### ISSUE THREAD

**Issue by loeschg** [jitpack/jitpack.io#142]
Projects can't seem to find the library even when adding

```
repositories {
	    maven {
	        url "https://jitpack.io"
	    }
	}
```

```
Error:(25, 13) Failed to resolve: com.github.loeschg:android-image-cropper:1.0.5
```

Not sure where to being the troubleshooting steps. Any help would be great!

**Comment by jitpack-io** [comment]
Hi @loeschg 
A good starting point is to look at the build log:
https://jitpack.io/com/github/loeschg/android-image-cropper/1.0.5/build.log

The main issue here is that build.gradle calls this script
https://raw.githubusercontent.com/ArthurHub/release-android-library/master/android-release-aar.gradle
which copies build artifacts to `"${buildDir}/release/${version}"` and not to $HOME/.m2/repository. So JitPack doesn't know where to find them.

One way to work around this is to use the android maven plugin instead of the script:
https://jitpack.io/docs/ANDROID/
Would that work for you?

**Comment by loeschg** [comment]
@jitpack-io thanks! Taking a look.

**Comment by loeschg** [comment]
:+1: that did the trick. Thanks!
