### ISSUE TITLE
BottomSheet/0dc7a49ca0 build issue

### ISSUE THREAD

**Issue by nbarraille** [jitpack/jitpack.io#149]
Log https://jitpack.io/com/github/soarcn/BottomSheet/0dc7a49ca0/build.log

**Comment by jitpack-io** [comment]
Fails because it includes this script https://raw.githubusercontent.com/soarcn/gradle/master/maven_push.gradle
which tries to upload to maven central.

Would work if it used properties for repository url's like here:
https://github.com/chrisbanes/gradle-mvn-push/blob/master/gradle-mvn-push.gradle#L24-L32
