### ISSUE TITLE
AccountNavigationView/af8ecb1a07 build issue

### ISSUE THREAD

**Issue by trbnb** [jitpack/jitpack.io#179]
Log https://jitpack.io/com/github/trbnb/AccountNavigationView/af8ecb1a07/build.log

**Comment by jitpack-io** [comment]
Hi

Would be best to add the android-maven plugin to the project. There's docs and an example project on jitpack.io/docs/

**Comment by trbnb** [comment]
Thanks for the quick reply. I had this in the project before but removed it because of a different error message that confused me.

Now the android-maven plugin is back in again and I'm getting a "`java.lang.IllegalStateException: buildToolsVersion is not specified.`" error while the buildToolVersion is specified as "23.0.0".
Here is the new log: https://jitpack.io/com/github/trbnb/AccountNavigationView/8de9d53e93/build.log

**Comment by jitpack-io** [comment]
Oh, right, that's caused by a mismatch in gradle version and the android-maven plugin version: 
https://github.com/dcendents/android-maven-gradle-plugin#note-on-releases
Unfortunately the error message doesn't say it.

Works after upgrading to gradle 2.4 https://github.com/jitpack-io/AccountNavigationView/commit/e0a7f5cecd1909eb459ced7dff579f5e8018a505

**Comment by trbnb** [comment]
Thanks a lot! That did the trick.
