### ISSUE TITLE
Nucleolus/1.0.0 build issue

### ISSUE THREAD

**Issue by jackmiras** [jitpack/jitpack.io#194]
Log https://jitpack.io/com/github/jackmiras/Nucleolus/1.0.0/build.log

**Comment by jitpack-io** [comment]
Hi @jackmiras 
Thanks for the bug report! Working on a fix

**Comment by jitpack-io** [comment]
Hi @jackmiras 
Upon closer look it looks like the 1.0.0 tag was placed on gh-pages branch and not on master. That's why it can't find a build file.

**Comment by jackmiras** [comment]
I fix this problem with the branch but now every time i try use my github project as dependency i get this error:
Error:Could not find com.github.jackmiras:nucleolus:1.0.0.
Required by:  
qfome-android:app:unspecified
Search in build.gradle files

**Comment by jitpack-io** [comment]
The reason is that 1.0.0 already existed before and it's cached on JitPack. 
The best option now is to create a completely new tag. Also would recommend trying out with a commit id as the version. Then if you're happy with it just add a tag on that commit.
Alternatively, if you sign in on jitpack.io then you can remove that version and build a new one.

**Comment by jackmiras** [comment]
I have created a new tag 3.0.0 but i still getting the same error:
Error:Could not find com.github.jackmiras:nucleolus:3.0.0.
Required by:
qfome-android:app:unspecified
Search in build.gradle files

**Comment by jitpack-io** [comment]
The best way to troubleshoot is to look at the log file:
https://jitpack.io/com/github/jackmiras/nucleolus/3.0.0/build.log

Currently theres this error:
```
:app:processReleaseResources/build/app/src/main/res/values/styles.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
```

also good idea to try building with gradle on your own machine. that way errors are caught quickly.

**Comment by jackmiras** [comment]
I fix the problem with 'Theme.AppCompat.Light.DarkActionBar' but now I get a new error:
Warning:Module 'com.github.jackmiras:nucleolus:4.0.0' depends on one or more Android Libraries but is a jar
Apparently has a conflict between compile 'com.android.support:appcompat-v7:23.0.1' from test-project and nucleolus. Exists a way to fix this without remove support dependency from nucleolus or test-project?

**Comment by jitpack-io** [comment]
Ok, it seems both the app and the library are pubished on JitPack. Not sure if that is your intention.
This is because the app is defined as a library:
https://github.com/jackmiras/nucleolus/blob/master/app/build.gradle#L1

if that was changes to an application then it should work. 

The other option is to get the library on its own with this dependency:
`compile 'com.github.jackmiras.nucleolus:nucleolus:4.0.0'`

**Comment by jackmiras** [comment]
I managed to solve the problems that were going on with dependence however I still can not remove the releases that are in JitPack cache in order to use a corresponding release version of the real version.

**Comment by jitpack-io** [comment]
Ok, will have a look at that.
