### ISSUE TITLE
Jitpack build fails - android-geocities-theme/1.0.0 build

### ISSUE THREAD

**Issue by duckinferno** [jitpack/jitpack.io#2089]
Log https://jitpack.io/com/github/dvoiss/android-geocities-theme/1.0.0/build.log

The failing jitpack build causes a gradle sync error with the dependency
`Failed to resolve: com.github.dvoiss:android-geocities-theme:1.0.0 `

**Comment by dvoiss** [comment]
Thanks for creating this @duckinferno. The specific error in that log about using the `google()` repo short-hand has been fixed by just not using it. 

But there is still another error that I cannot fix:

Log https://jitpack.io/com/github/dvoiss/android-geocities-theme/-1.0.0-g3f2f159-13/build.log

I've tried a bunch of random things to fix this, such as changing gradle versions, removing gradle wrapper, adding a `.jitpack.yml` file, using the same version/configuration of another project I have ([literallytoast](https://github.com/dvoiss/literallytoast) that uses jitpack successfully.

^ I always end up with the error above.

**Comment by duckinferno** [comment]
Wow I totally thought this was in your git repo :)

It seems like you haven't pushed your gradle wrapper jar to the repo, that seems like quite low hanging fruit but have you tried it? (see https://github.com/jitpack/jitpack.io/issues/1167)

**Comment by dvoiss** [comment]
Thanks, resolved!

For some reason my global `.gitignore` had `*.jar` in it :(
