### ISSUE TITLE
ParseFacebookUtils-Android/v4-1.10.3 build issue

### ISSUE THREAD

**Issue by crtlib** [jitpack/jitpack.io#228]
Log https://jitpack.io/com/github/ParsePlatform/ParseFacebookUtils-Android/v4-1.10.3/build.log

**Comment by jitpack-io** [comment]
Hi,
the issue is its trying to deploy to sonatype. Would work if the build script used properties like here 
https://github.com/chrisbanes/gradle-mvn-push/blob/master/gradle-mvn-push.gradle#L24-L27
I guess its possible to submit a PR to them. We might be able to solve it on our end as well but need to look into it more

**Comment by jitpack-io** [comment]
Fixed
