### ISSUE TITLE
Project name with dots cannot be added to a maven build

### ISSUE THREAD

**Issue by jcornaz** [jitpack/jitpack.io#2372]
As already stated in #14 and #1145, project containing dots in their name, are not downloaded.

A work around has been found to replace the `.` by `~`. But this is not enough.

1. `~` is not a valid character for groupId when using Maven.
2. The examples on [jitpack.io](https://jitpack.io/#Kotlin/kotlinx.coroutines/9faa61eeabbc2c111431fb25aa8947363d842d3e) don't tell to use the work-around.

**Comment by mbe24** [comment]
A working solution for Maven would be very much appreciated.

**Comment by jcornaz** [comment]
@jitpack-io Any update on this?

**Comment by jitpack-io** [comment]
Indeed, putting dots in artifact name is ambiguous for JitPack to resolve.
`~` doesn't work in Maven because it uses this regex to validate: [`[A-Za-z0-9_\\-.]+`](https://github.com/apache/maven/blob/maven-3.3.9/maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java#L67). Based on that we can only pick `_` and `-` as replacements however those are valid characters in GitHub repositories.

**Comment by jcornaz** [comment]
@jitpack-io Why not correcly resolve the dots in the name instead?

**Comment by mbe24** [comment]
Maybe there's a viable Maven workaround. I've created a question on [Stackoverflow](https://stackoverflow.com/questions/52295421/use-maven-dependency-with-special-characters-in-artifactid).

Is it possible to use a local Maven repository, but there are manual steps involved. See [this answer](https://stackoverflow.com/a/36602256/1809463) on Stackoverflow.

**Comment by mbe24** [comment]
@jitpack-io What about creating a subdomain (e.g. repo.jitpack.io) where a non-maven character is used as directory indicator (or however you call the function `.` currently has).
