### ISSUE TITLE
EasyAndroidAnimations/0.8 build issue

### ISSUE THREAD

**Issue by Morfeusys** [jitpack/jitpack.io#252]
Log https://jitpack.io/com/github/2359media/EasyAndroidAnimations/0.8/build.log

**Comment by jitpack-io** [comment]
Hi @Morfeusys 
Fixed! Sorry about that!

**Comment by Morfeusys** [comment]
Fixed, but it doesn't work! Now the build contains redundant files which break an app build.
Please fix. Thanks!

**Comment by jitpack-io** [comment]
Hi
Sure, will have a look. Is the app also on GitHub?

**Comment by Morfeusys** [comment]
Nope. The buildToolsVersion is "22.0.1" in my app. It's important.
There are resource files in the resulting .aar. This breaks the build.
Thanks.

**Comment by jitpack-io** [comment]
I see. Looks like v 0.8 is broken and was fixed in this commit https://github.com/2359media/EasyAndroidAnimations/commit/e51321fdac4c54237184f5aaef8ef0d9fdef2d3f

You could try the latest version: `compile 'com.github.2359media:EasyAndroidAnimations:07f1306'`
or ask the maintainers to create a new release that includes it.
