### ISSUE TITLE
jmx_exporter/2db4f0c8bb build

### ISSUE THREAD

**Issue by picadoh** [jitpack/jitpack.io#2862]
Log https://jitpack.io/com/github/prometheus/jmx_exporter/2db4f0c8bb/build.log

**Comment by jitpack-io** [comment]
Hi @picadoh 

The cause of the build failure seems to be:
`UnsupportedClassVersionError: org/codehaus/mojo/buildhelper/ReserveListenerPortMojo : Unsupported major.minor version 51.0`

51 is Java 7 however JitPack is building with Java 6 because that's what the pom.xml file specifies as target version.

If you need to run the build with Java 7 then that's configurable in jitpack.yml:
https://jitpack.io/docs/BUILDING/#custom-commands

**Comment by picadoh** [comment]
So if I got it correctly, Jitpack selects the compiler based on the maven-compiler-plugin target version?

**Comment by jitpack-io** [comment]
Yes
