### ISSUE TITLE
Add support for building with Bazel

### ISSUE THREAD

**Issue by edenman** [jitpack/jitpack.io#3129]
I would like to point my app at a forked version of Dagger, but Dagger builds with Bazel.  I tried adding a custom build step to call bazel, but (perhaps obviously) it's not installed:

https://jitpack.io/com/github/edenman/dagger/c5e710b/build.log

**Comment by edenman** [comment]
I ended up just building and pushing my artifact to a dummy maven repo.  Custom commands definitely possible but I'm probably not gonna spend the time to figure it out at this point.

**Comment by JohnAZoidberg** [comment]
With [bazelisk](https://github.com/bazelbuild/bazelisk) it's very easy to get bazel. You just need to download a single binary and it downloads and configures bazel by itself.

Together with [rules_jvm_external](https://github.com/bazelbuild/rules_jvm_external/blob/master/docs/api.md#java_export) I can build and export to a maven repository.

Example: https://github.com/JohnAZoidberg/j-antplus/pull/8

The only issue I encountered is that fetching the artifact fails because it can't get some dependencies of my project.

**Comment by JohnAZoidberg** [comment]
> The only issue I encountered is that fetching the artifact fails because it can't get some dependencies of my project.

To clarify: I can fetch my own JAR from jithub but maven wants to fetch my dependencies from jithub too and they aren't.

**Comment by vorburger** [comment]
FYI I've found this issue and it has inspired me to put something similar together; just in case this is ever useful to others:

* https://github.com/enola-dev/enola/issues/970
* https://github.com/enola-dev/enola/pull/974/files
* https://github.com/jitpack/jitpack.io/issues/6762
* https://github.com/enola-dev/enola/pull/976 #uglyButWorksHack to install `bazelisk` on JitPack VM

This got me to a point where it started building, but then appears to timeout?! It says _"Status: Error"_ but it's not very clear from e.g. https://jitpack.io/com/github/vorburger/enola/jitpack2-bazelisk-e6742e9c7f-1/build.log what happened, but presumably it OOM'd. (Because, in my project, Bazel rebuilds ProtoBuf from sources, which is kind of stupid; this will eventually get improved in Bazel.)

PS: What I have also realized (AFTER 😃) is that without any caching, this is not very "efficient", because Bazel's entire architecture kind of assumes that it can keep state around between builds. (On GitHub Actions once can use https://github.com/bazel-contrib/setup-bazel for this.) @jitpack-io I don't suppose that it's possible to put something into `jitpack.yml` to cache certain directories between builds? From your documentation is appears that you may already be caching certain Gradle & Maven directories... if it was possible to list other customer directories to cache in `jitpack.yml`, that would be cool!

**Comment by vorburger** [comment]
> Bazel rebuilds ProtoBuf from sources, which is kind of stupid; this will eventually get improved in Bazel.

==> https://github.com/protocolbuffers/protobuf/issues/19558
