### ISSUE TITLE
jitpack is asking for an access token for a public github repository

### ISSUE THREAD

**Issue by desertkun** [jitpack/jitpack.io#369]
When I run my gradle I get:

    Could not resolve all dependencies for configuration ':desktop:compile'.
    > Could not resolve com.github.desertkun:kryo-shaded:3.0.3-RC2.
       > Could not HEAD 'https://jitpack.io/com/github/desertkun/kryo-shaded/3.0.3-RC2/kryo-shaded-3.0.3-RC2.pom'. 
         Received status code 401 from server: No access token provided

Because this url requires authorisation:
https://jitpack.io/com/github/desertkun/kryo-shaded/3.0.3-RC2/kryo-shaded-3.0.3-RC2.pom (from https://github.com/desertkun/kryo)

However, another public git repository goes ok:
https://jitpack.io/com/github/desertkun/kryonet/2.22.0-RC3/kryonet-2.22.0-RC3.pom (from https://github.com/desertkun/kryonet)

Thank you!

**Comment by jitpack-io** [comment]
Hi

Since kryo-shaded is a sub-module, the dependency is:
`com.github.desertkun.kryo:kryo-shaded:3.0.3-RC2`

JitPack was asking for a username because there is no public GitHub repo called kryo-shaded. It might be private but we have no way of knowing it without an access token.

The other modules are also listed at the end of the log:
https://jitpack.io/com/github/desertkun/kryo/3.0.3-RC2/build.log

Cheers!

**Comment by desertkun** [comment]
Thank you for the response. How can I deal with that then? Should I copy `kryo` github repository to `kryo-shaded`? Wouldn't that be duplication?

**Comment by jitpack-io** [comment]
You can already use kryo-shaded but only using this dependency: 
`compile 'com.github.desertkun.kryo:kryo-shaded:3.0.3-RC2'`

Since it's a multi-module project the syntax for dependencies is slightly different https://jitpack.io/docs/BUILDING/#multi-module-projects

**Comment by desertkun** [comment]
That solved my issue, thank you very much!

**Comment by jitpack-io** [comment]
:+1:
