### ISSUE TITLE
Unexpected version in SNAPSHOT build name

### ISSUE THREAD

**Issue by noamtamim** [jitpack/jitpack.io#3714]
When building a SNAPSHOT of my library, JitPack adds a version number to the version string which is not related to the actual content so it's very confusing.
For example in this build:
https://jitpack.io/com/kaltura/playkit-android/profiler-v3.4.5-g131172d-175/build.log

I don't understand where `v3.4.5` is coming from. This string does not appear anywhere in my code (the real version 3.4.5 was released on April of 2018 and we had plenty of releases since). 

Actually, since this is a snapshot build from a development branch, **it doesn't have a version number**.

**Comment by jitpack-io** [comment]
Hi,

Snapshot versions are derived from `git describe` command. JitPack runs it before the build and the result in the build log is:
`v3.4.5-175-g131172d`
Basically 175 commits since tag v3.4.5 on this branch and the commit sha is 131172d.

If you run git describe locally for the same commit then you should get the same output. If not, let us know
