### ISSUE TITLE
Maven build successed but no artifact

### ISSUE THREAD

**Issue by sytolk** [jitpack/jitpack.io#3754]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/liferay/liferay-faces-bridge-api/master-5f6d4a2514-1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
yes

- What error are you seeing?
I see build successful but it stay in red and no artifact is provided

**Comment by jitpack-io** [comment]
Hi,

There are a few unusual messages in the Maven log:
```
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Skipping artifact installation
```
which probably is why the library is not published.

**Comment by sytolk** [comment]
But I can successful install this package in my local maven repo.. maybe the reason for this is project structure (root POM is missing) ?
https://github.com/liferay/liferay-faces-bridge-api

If its possible to run mvn install in folder https://github.com/liferay/liferay-faces-bridge-api/tree/master/bridge-api

**Comment by stiemannkj1** [comment]
@sytolk,
This seems it is caused by jitpack #1701. I'd recommend using the `mavenCentral()` repository for Liferay Faces for now. Even if we add a parent `pom.xml` in `liferay/liferay-faces-bridge-api` that won't fix the issue for old releases.

I also noticed some other issues with jitpack and Liferay Faces: when I try to get the following artifact:

```
runtime(group: 'com.github.liferay.liferay-faces-bridge-impl', name: 'com.liferay.faces.bridge.impl', version: '4.1.2')
```

jitpack thinks that the Util and Bridge API dependency versions are `4.1.2` which is incorrect. Util is version `3.1.0`, and Bridge API is version `4.1.0`. So I think jitpack will need to improve its maven support before it can be used with Liferay Faces.

**Comment by jitpack-io** [comment]
Since there is no pom.xml the moment JitPack finds a pom.xml in bridge-spec directory and installs that. 
It is also possible to configure custom build commands to install differently: https://jitpack.io/docs/BUILDING/#custom-commands
