### ISSUE TITLE
tag prefix with "v"

### ISSUE THREAD

**Issue by zhong-j-yu** [jitpack/jitpack.io#384]
If the github tag is prefixed with `v`, e.g. `v1.2.3`, can we reference it in dependent POMs without the `v`? For example

        <version>1.2.3</version>

This used to work, but not any more?

What's your suggestion? Currently I workaround it by adding tag `1.2.3` without the `v` prefix.

**Comment by jitpack-io** [comment]
Hi!

You're right, it used to be a feature but in hindsight it was probably not a great idea. First of all it's possible to add two tags - one with `v` and one without on different commits. If JitPack supports both then its also more confusion for the user - which one should I use? Or when users report bugs you have to try to reproduce it on two versions.

Using tags without the `v` is a good practice because it's non-ambiguous. Works well with JitPack and build tools. Would suggest doing that as you have already.

**Comment by zhong-j-yu** [comment]
That makes sense, thanks. Who needs `v` anyway :)

**Comment by jitpack-io** [comment]
And looks like Semver removed `v` from the spec in the latest version http://semver.org/spec/v2.0.0.html

**Comment by zhong-j-yu** [comment]
I agree with you -- people use various patterns for tags and versions, it's pretty dangerous to try to parse and normalize some of them. This is a messy situation, and you'll probably hear more complaints:) Maybe a footnote in your docs would clarify it up.

Once again, I really appreciate your product and service:) Thanks.
