### ISSUE TITLE
SignalA/a29ed9caf8 build

### ISSUE THREAD

**Issue by davrbk** [jitpack/jitpack.io#385]
Log https://jitpack.io/com/github/erizet/SignalA/a29ed9caf8/build.log

Errors from the log:
```
Execution failed for task ':SignalA:uploadArchives'.
> Could not publish configuration 'archives'
   > Failed to deploy artifacts: Could not transfer artifact com.github.erizet.signala:signala:aar:0.20-20160118.100348-1 
from/to remote (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: 
https://oss.sonatype.org/content/repositories/snapshots/com/github/erizet/signala/signala/0.20-SNAPSHOT/signala-0.20-20160118.100348-1.aar. 
Return code is: 401, ReasonPhrase: Unauthorized.
```

**Comment by jitpack-io** [comment]
Hi

The problem is that the project tries to upload to sonatype.org. The url's are hardcoded:
https://github.com/erizet/SignalA/blob/master/maven_push.gradle#L7-L10

It's easy to make it work with JitPack, they just have to use properties instead of hardcoded urls like here:
https://github.com/jitpack-io/gradle-mvn-push/blob/master/gradle-mvn-push.gradle#L24-L32

So probably best to ask the project maintainers or submit a PR.

**Comment by jitpack-io** [comment]
Fixed
