### ISSUE TITLE
minidns/66ae2a93be build

### ISSUE THREAD

**Issue by mariotaku** [jitpack/jitpack.io#397]
Log https://jitpack.io/com/github/rtreffer/minidns/66ae2a93be/build.log

**Comment by jitpack-io** [comment]
Hi

Looks like the project is quite old. One of the problems is that there's no gradle wrapper in the project so JitPack doesn't know which version to use.

**Comment by mar-v-in** [comment]
@jitpack-io the actual problem is that line
`Can't find android.jar for 9 API. Please install corresponding SDK platform package`. According to [this Docker file](https://github.com/jitpack/dockerfiles/blob/master/android/Dockerfile#L18) you are not installing android-9 api support. Adding a gradle wrapper will not help here.

**Comment by jitpack-io** [comment]
@mar-v-in is right, missing android-9 api is a bigger issue. Unfortunately there are no plans to support it as it has very low demand. Sorry for the confusion.
