### ISSUE TITLE
Version badges don't seem to be working

### ISSUE THREAD

**Issue by afollestad** [jitpack/jitpack.io#429]
This badge shows version 0.7.7:

[![Release](https://jitpack.io/v/afollestad/app-theme-engine.svg)](https://jitpack.io/#afollestad/app-theme-engine)

But the current is 1.0.0, and it built successfully: https://jitpack.io/#afollestad/app-theme-engine

**Comment by jitpack-io** [comment]
Hi

The image itself is updated but they don't instantly update in the readme because GitHub caches images. It is possible to purge that image from cache manually: https://help.github.com/articles/why-do-my-images-have-strange-urls/#removing-an-image-from-camos-cache

Image on jitpack:
- https://jitpack.io/v/afollestad/app-theme-engine.svg

**Comment by afollestad** [comment]
Hmm, I don't remember having to do that with shields.io, there must be a way around that which is automatic. 

Thank you, though!
