### ISSUE TITLE
Build Faile！ The java version too old

### ISSUE THREAD

**Issue by GordonGgx** [jitpack/jitpack.io#4295]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/GordonGgx/AndroidFx/V1.0/build.log
- java.lang.UnsupportedClassVersionError: org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Thank you!

**Comment by dcmoeller** [comment]
Seems I've stumbled upon a similar issue with a Gradle build of my current project: Referencing a public project on GitLab failed. A look into the `build.log` file gives the root cause:
```
[...]
> Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.
[...]
ERROR: No build artifacts found
```
The project to get built requires JDK 11 (at least), your build infrastructure provides JDK 8.
Upgrade to JDK 11 appreciated :-)

Regards

Christian

**Comment by dcmoeller** [comment]
> Seems I've stumbled upon a similar issue with a Gradle build of my current project: Referencing a public project on GitLab failed. A look into the `build.log` file gives the root cause:
> 
> ```
> [...]
> > Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.
> [...]
> ERROR: No build artifacts found
> ```
> 
> The project to get built requires JDK 11 (at least), your build infrastructure provides JDK 8.
> Upgrade to JDK 11 appreciated :-)
> 
> Regards
> 
> Christian

OK, found the corresponding help chapter: https://jitpack.io/docs/BUILDING/#java-version
