### ISSUE TITLE
Failed build

### ISSUE THREAD

**Issue by 6u5t4v** [jitpack/jitpack.io#4416]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/#WyvenCraft/WyvenCore

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Not sure what this mean :I

- What error are you seeing?
https://pastebin.com/dA1fCiLk

Thank you!

**Comment by tommyettinger** [comment]
In the logs for your 2.0.0 release, there's this error:
```
[ERROR] Failed to execute goal on project WyvenCore: Could not resolve dependencies for project com.wyvencraft:WyvenCore:jar:1.0.0: Could not find artifact com.destroystokyo.paper:paper:jar:1.16.4-R0.1-SNAPSHOT in papermc (https://papermc.io/repo/repository/maven-public/) -> [Help 1]
```

It looks like some dependencies from papermc can be found, but not a SNAPSHOT, since snapshots often don't last after the version is released. It's not a good idea to depend on a SNAPSHOT in a stable release like 2.0.0. The 2.0.0 release will never build as a result of that dependency failure; you can make a 2.0.1 release or whatever version you want once you fix it. You can use commits as versions (see the commits tab), and use that to evaluate if the code is ready for a release yet.
