### ISSUE TITLE
Pdfbox-layout Build failed on Jitpack.  Not able to pull dependency via maven

### ISSUE THREAD

**Issue by Philipp-Geoinformatik** [jitpack/jitpack.io#4520]
https://jitpack.io/com/github/ralfstuckert/pdfbox-layout/1.0.0

5 errors
4 warnings
:pdfbox2-layout:javadocJar
:pdfbox2-layout:sourcesJar
:pdfbox2-layout:install

BUILD SUCCESSFUL

**Comment by amottier** [comment]
According to the [build log](https://jitpack.io/com/github/ralfstuckert/pdfbox-layout/1.0.0/build.log) errors were related to Javadoc syntax issues only.

Version 1.0.1 fix that:
- https://github.com/ralfstuckert/pdfbox-layout/compare/1.0.0...1.0.1#diff-43b0df7edc697c17858202b79438dbbe54fbe747ffbae3c129011ea3279524f8
- https://github.com/ralfstuckert/pdfbox-layout/compare/1.0.0...1.0.1#diff-a40ab6625cd5834c42ea38929248a8e39df583cba1732de3ed4dd0f697e2a03f
- https://github.com/ralfstuckert/pdfbox-layout/compare/1.0.0...1.0.1#diff-d2aa79ae638f492433f9643ad6dbfb7fe2e44790efcb6fb4704c34d07974bf42

So I guess the solution here is to accept that version 1.0.0 will not be available from Jitpack and pull version 1.0.1 instead.

Note that version 1.0.1 includes other changes one being the support of Java 8 instead of Java 7 for version 1.0.0.
