### ISSUE TITLE
Unable to build Android library targeting Android 12 (API 31)

### ISSUE THREAD

**Issue by DanielGalarza** [jitpack/jitpack.io#4808]
Please provide:

- Link to build log from https://jitpack.io: https://jitpack.io/com/github/CirrusMD/cirrusmd-android/main-c6a5d83d3e-1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes

- What error are you seeing?
Jitpack won't build my new tag, nor any of my up to date branches 

Thank you!

**Comment by shavinda-rabichandran-cko** [comment]
I experienced the same issue with my build for the last 2 days.
I found that when  targeting API 31, you must use Java 11, otherwise the build fails.

@DanielGalarza Have a look at the instructions on [setting the Java version](https://jitpack.io/docs/BUILDING/#java-version) using a `jitpack.yml` file. This resolved my build issues.

@jitpack-io You could add a fix by taking into account the target Android SDK version when determining the default Java version to use rather than defaulting to Java 8. (i.e. API 31 and above should use JAVA 11 by default)

**Comment by DanielGalarza** [comment]
> I experienced the same issue with my build for the last 2 days. I found that when targeting API 31, you must use Java 11, otherwise the build fails.
> 
> @DanielGalarza Have a look at the instructions on [setting the Java version](https://jitpack.io/docs/BUILDING/#java-version) using a `jitpack.yml` file. This resolved my build issues.
> 
> @jitpack-io You could add a fix by taking into account the target Android SDK version when determining the default Java version to use rather than defaulting to Java 8. (i.e. API 31 and above should use JAVA 11 by default)

Thank you for posting this! This is what I was looking for!
