### ISSUE TITLE
material-dialogs/de798e04c3 build

### ISSUE THREAD

**Issue by ashughes** [jitpack/jitpack.io#522]
Log https://jitpack.io/com/github/afollestad/material-dialogs/de798e04c3/build.log

**Comment by jitpack-io** [comment]
Hi

The build is failing because this repo is using an alpha version of the android plugin:

`Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to ...`

Should work after upgrading the gradle android plugin to:
`classpath 'com.android.tools.build:gradle:2.1.0+'`
