### ISSUE TITLE
dagger/1a5b3623c1 build

### ISSUE THREAD

**Issue by burntcookie90** [jitpack/jitpack.io#534]
Log https://jitpack.io/com/github/square/dagger/1a5b3623c1/build.log

**Comment by jitpack-io** [comment]
Hi @burntcookie90 

The pom.xml for dagger specifies java 1.6 https://github.com/square/dagger/blob/master/pom.xml#L44
So that's the version that jitpack uses to build. At the same time the nio Path class from java 1.7 is used in the project and it can't be found. Might be worth raising an issue in the dagger project itself
