### ISSUE TITLE
Redirect to latest javadoc

### ISSUE THREAD

**Issue by jitpack-io** [jitpack/jitpack.io#568]
We should have a way to open the latest version of javadoc - one that corresponds to the latest release.

This is already possible for snapshots but that only provides javadoc for the latest commit.

A few options:
- https://jitpack.io/com/github/user/repo/latest/javadoc/
- https://jitpack.io/com/github/user/repo/javadoc/
- https://javadoc.jitpack.io/com/github/user/repo/
- A special query parameter

**Comment by gdejohn** [comment]
I like [jitpack.io/com/github/user/repo/javadoc/](https://jitpack.io/com/github/user/repo/javadoc/). I think [jitpack.io/com/github/user/repo/**latest**/javadoc/](https://jitpack.io/com/github/user/repo/latest/javadoc/) suggests that it does what [jitpack.io/com/github/user/repo/**master-SNAPSHOT**/javadoc/](https://jitpack.io/com/github/user/repo/master-SNAPSHOT/javadoc/) already does. Makes sense to me to ask for snapshot docs explicitly, and if no history marker is provided, it defaults to the latest *release* (instead of the latest commit), which presumably is what you want most of the time.

**Comment by jitpack-io** [comment]
Hi all,

This should be working now. To get the javadoc for latest release use:
* `https://jitpack.io/com/github/USER/REPO/latest/javadoc/`
