### ISSUE TITLE
Subscription is Not Getting Activated

### ISSUE THREAD

**Issue by ishaan1607** [jitpack/jitpack.io#5742]
Please provide:

- Link to build log from https://jitpack.io  [Logs](https://jitpack.io/com/github/NateshR/LikeMinds-Android-SDK/v1.12.4/build.log)

Our [project](https://jitpack.io/#NateshR/LikeMinds-Android-SDK) is showing inactive since yesterday. And when trying to complete the payment for the subscription. The payment is getting refunded. 

Please look into the matter. Our customers are getting affected by this issue. Please to resolve issue as soon as possible. We have also raised the matter in support as well.

**Comment by NateshR** [comment]
@jitpack-io please get this issue resolved, we are facing this and our customers are not able to use jitpack, otherwise we will have to shift to some other artifaact deployment

**Comment by gouravspyne** [comment]
Hi @jitpack-io,

Yesterday, our account suddenly became inactive despite having an active yearly plan that started in February 2023. Due to this confusion, our team made an additional payment today, thinking that the subscription had expired. However, even after the second payment, the account remains inactive.

Our usage of Jitpack is crucial for our client Swiggy and its restaurant partners. Due to the account's inactive status, their services have been disrupted since yesterday.

Account details:
Email- tech@spyne.ai

**Comment by customlib** [comment]
Hi @jitpack-io,
When I pay for a subscription after the payment, the account remains inactive. Support is slow. Please help us.

**Comment by customerglu-code** [comment]
Hey, our subscription has been marked as inactive, we made the payment twice, and both times it went through, but the subscription still shows as inactive. Please help resolve immediately.
