### ISSUE TITLE
JitPack support not responding. Subscription not active  message for Paid repository

### ISSUE THREAD

**Issue by tech-app-innovation** [jitpack/jitpack.io#5788]
Hii @jitpack-io  please also my issue the issue is same mentioned by @gouravspyne  please resolve this issue we are losing users show account status inactive.

![image](https://github.com/jitpack/jitpack.io/assets/106601695/ae2d14e2-18fb-4282-9263-9d25e599f405)

![image](https://github.com/jitpack/jitpack.io/assets/106601695/36ce3f12-b087-4185-8f2c-17b9332d61e9)

![Screenshot_18](https://github.com/jitpack/jitpack.io/assets/106601695/b8f08b6d-9aa8-4d20-bf49-fc39d59b0335)

**Comment by gouravspyne** [comment]
Hi,
This issue is resolved on my account because the payment did not go through
each time I tried so I drop a mail to Jitpack and their team share the
payment link over the mail. With the payment link, I was able to make
a successful payment and the issue was resolved.

Mail from jitpack:

Hi

No worries, we have enabled free trial and the account is active now.
It seems the latest payment didn't go fully through. Attaching screenshot
from our billing system.
The payment from February also didn't go through so we will send an invoice
with manual payment links.
Please let us know if we can assist further

Regards,
*Gourav*
*TEAM LEAD,*
*Spyne.ai <http://Spyne.ai> 🚀 *
Regards,

**Comment by shuftipro** [comment]
@gouravspyne 
Can you please share Jitpack support email because i submit multiple feedback but no response.

**Comment by tech-app-innovation** [comment]
@gouravspyne please provide me support email

**Comment by tech-app-innovation** [comment]
@gouravspyne  if you do  some small help to us please share us email i am trying from last 4-5 day i didn't find any way to contact to jitpack and i am running private repository please help me or also you can send me email on techappinnovation@gmail.com

**Comment by gouravspyne** [comment]
Hi,
Go to https://jitpack.io/ and scroll down to the end of the page where you
will find a support option to contact jitpack. PFA for the example
screenshot.

[image: Screenshot 2023-08-10 at 8.10.29 AM.png]
Regards,
*Gourav*
*TEAM LEAD,*
*Spyne.ai <http://Spyne.ai> 🚀 *

**Comment by tech-app-innovation** [comment]
@gouravspyne i already submitted upto 5-7 time but they don't reply

**Comment by gouravspyne** [comment]
This is how I reached Jitpack team.

Regards,
*Gourav*
*TEAM LEAD,*
*Spyne.ai <http://Spyne.ai> 🚀 *
