### ISSUE TITLE
Jitpack.io showing status Inactive even subscribe last night

### ISSUE THREAD

**Issue by shuftipro** [jitpack/jitpack.io#5789]
Hi Team,

I am writing to bring to your attention an issue we are currently encountering on Jitpack.io. Our client is experiencing a status code 403 error, which is attributed to a subscription expiration. Despite having recently renewed our subscription plan, the status remains inactive even after a span of 12 hours.

In light of this situation, I kindly request your prompt assistance in investigating and resolving this matter. The urgency arises from the fact that our clients are eagerly awaiting a resolution. Your timely attention to this concern is greatly appreciated.

<img width="1134" alt="Screenshot 2023-08-09 at 11 29 33 AM" src="https://github.com/jitpack/jitpack.io/assets/34159299/ec990143-0c79-47f6-85f9-35deb71f387c">

**Comment by Spyne-Tech** [comment]
Hi,
This issue is resolved on my account because the payment did not go through each time I tried so I drop a mail to Jitpack and their team share the payment link over the mail. With the payment link, I was able to make a successful payment and the issue was resolved.

Mail from jitpack:
Hi,
No worries, we have enabled free trial and the account is active now.
It seems the latest payment didn't go fully through. Attaching screenshot from our billing system.
The payment from February also didn't go through so we will send an invoice with manual payment links.
Please let us know if we can assist further

Regards,
GouravTEAM LEAD,[Spyne.ai](http://spyne.ai/)

**Comment by shuftipro** [comment]
@Spyne-Tech 
Can you please share email of Jitpack because i submit multiple feedback but no response from Jitpack.

**Comment by Spyne-Tech** [comment]
Hi,
Go to https://jitpack.io/ and scroll down to the end of the page where you will find a support option to contact jitpack. PFA for the example screenshot.
<img width="1440" alt="Screenshot 2023-08-10 at 8 10 29 AM" src="https://github.com/jitpack/jitpack.io/assets/120455818/f1ed7604-c91f-4a3a-a3d9-3c5fef26edab">
