### ISSUE TITLE
Jitpack Server is down unable download any library broken our CI/CD

### ISSUE THREAD

**Issue by GomajiMobile** [jitpack/jitpack.io#6454]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?
- What went wrong:
Could not determine the dependencies of task ':app:compileDevDebugKotlin'.

> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Could not resolve com.github.gomaji:KLog:-SNAPSHOT.
     Required by:
         project :app
      > Could not resolve com.github.gomaji:KLog:-SNAPSHOT.
         > Could not get resource 'https://jitpack.io/com/github/gomaji/KLog/-SNAPSHOT/KLog--b059ad2cae-1.pom'.
            > Could not HEAD 'https://jitpack.io/com/github/gomaji/KLog/-SNAPSHOT/KLog--b059ad2cae-1.pom'.
               > Read timed out
   > Could not resolve com.github.gomaji:material-calendarview:-SNAPSHOT.
     Required by:
         project :app
      > Could not resolve com.github.gomaji:material-calendarview:-SNAPSHOT.
         > Could not get resource 'https://jitpack.io/com/github/gomaji/material-calendarview/-SNAPSHOT/material-calendarview--2.0.5-ga0ec51c-1.pom'.
            > Could not HEAD 'https://jitpack.io/com/github/gomaji/material-calendarview/-SNAPSHOT/material-calendarview--2.0.5-ga0ec51c-1.pom'.
               > Read timed out
   > Could not resolve com.github.GomajiEvan.android-youtube-player:chromecast-sender:gomaji-SNAPSHOT.
     Required by:
         project :app > com.github.GomajiEvan:android-youtube-player:gomaji-SNAPSHOT:62317c753e-1
      > Skipped due to earlier error
   > Could not resolve com.github.GomajiEvan.android-youtube-player:core:gomaji-SNAPSHOT.
     Required by:
         project :app > com.github.GomajiEvan:android-youtube-player:gomaji-SNAPSHOT:62317c753e-1
      > Skipped due to earlier error

Thank you!

**Comment by FaciaMobile** [comment]
Facing the same issue.

**Comment by bash-celik** [comment]
Could be this: https://jfrog.com/blog/jcenter-sunset/

**Comment by ps-patryk** [comment]
> Could be this: https://jfrog.com/blog/jcenter-sunset/

I can confirm, I checked historical data and we experienced the same issues during the announced brownouts: 
```
Brownout Schedule:

July 30th, 7:00 AM – 8:00 AM (UTC) (1 hour)
July 30th, 6:00 PM – 7:00 PM (UTC) (1 hour)
August 5th, 7:00 AM – 11:00 AM (UTC) (4 hours)
August 5th, 6:00 PM – 10:00 PM (UTC) (4 hours)
August 7th, 1:00 PM – August 8th, 1:00 PM (UTC) (24 hours)
```

**Comment by Hatzen** [comment]
Just for documentation purpose, this issue is not really resolved. But old Repo Builds will fail when they still require jcenter or plugins for it.  
Usually the proper way to resolve these issues is to replace the old repos with working ones, either by updating or forking and updating if the maintainer is not merging PRs.  

I would really appreciate if we had some jitpack hooks to modify the repo source in a generic manner (which is not a long term solution)
As this is not possible and jitpack is not really an open source project i tried around for such things a little while https://github.com/Hatzen/OpenJitLibProvider 
but the repo is currently not a full replacement of jitpack and the current master is not working completly i guess, i dropped development for other projects at the moment, if anyone wants to contribute he is welcome.  
Best solution for everyone would be to fork not working repos and provide them for other people so they can continue using jitpack
