### ISSUE TITLE
Jitpack server is down, unable to get any of my dependencies/libraries.

### ISSUE THREAD

**Issue by FaciaMobile** [jitpack/jitpack.io#6458]
Jitpack server is down, our dependency was live. Now some of our clients are unable to get it.
Firstly we were unable to get the dependency, it was giving timeout.
Then issue updated, now it is returning us build failed issue.
Getting error on android studio while building gradle:
Failed to resolve: com.github.FaciaMobile:android-core:3.0.4

Build.log file:

> https://jitpack.io/com/github/FaciaMobile/android-core/3.0.4/build.log

It is mentioning error:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> > Could not resolve all files for configuration ':app:debugCompileClasspath'.
>    > Could not find com.kaopiz:kprogresshud:1.2.0.
>      Required by:
>          project :app
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> BUILD FAILED in 28s
> Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
> Publication: com.github.FaciaMobile:android-core:2.0.4
> Build tool exit code: 0
> Looking for artifacts...
> Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
> Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
> Looking for pom.xml in build directory and ~/.m2
> Found artifact: com.github.FaciaMobile:android-core:2.0.4
> 2024-08-19T14:11:51.474774809Z
> Exit code: 0
> 
> ⚠️ ERROR: No build artifacts found
> Expected artifacts in: $HOME/.m2/repository/com/github/FaciaMobile/android-core/2.0.4

<img width="664" alt="Screenshot 2024-08-20 at 10 52 12 AM" src="https://github.com/user-attachments/assets/5c9e23d8-4e8b-4a30-9549-f7c200e477da">

All of these versions were live and were in use, now all of these are down suddenly.
Please resolve it ASAP.

**Comment by FaciaMobile** [comment]
@jitpack-io Please have a look on it.

**Comment by Mr-Ramzan** [comment]
It is hapening on various libraries. and still facing this issue

**Comment by voronind-com** [comment]
Still happening.

**Comment by Hatzen** [comment]
> Still happening.

 Could not find com.kaopiz:kprogresshud:1.2.0.

was in jcenter https://mvnrepository.com/artifact/com.kaopiz/kprogresshud/1.2.0 

which was shut down.


So i copy the response of the related Issues:

Just for documentation purpose, this issue is not really resolved. But old Repo Builds will fail when they still require jcenter or plugins for it.
Usually the proper way to resolve these issues is to replace the old repos with working ones, either by updating or forking and updating if the maintainer is not merging PRs.

I would really appreciate if we had some jitpack hooks to modify the repo source in a generic manner (which is not a long term solution)
As this is not possible and jitpack is not really an open source project i tried around for such things a little while https://github.com/Hatzen/OpenJitLibProvider
but the repo is currently not a full replacement of jitpack and the current master is not working completly i guess, i dropped development for other projects at the moment, if anyone wants to contribute he is welcome.
Best solution for everyone would be to fork not working repos and provide them for other people so they can continue using jitpack
