### ISSUE TITLE
Building multi-module projects doesn't support repository names with `.`

### ISSUE THREAD

**Issue by kag0** [jitpack/jitpack.io#808]
Currently [multi-module projects](https://github.com/jitpack/jitpack.io/blob/master/BUILDING.md#multi-module-projects) require using a groupId like `com.github.User.Repo` when pulling the dependency. However, if the repo name has a `.` in it (eg. `my.project` would be `com.github.myuser.my.project`), the dependency will not be resolved (since presumably jitpack doesn't know where to split the domain and the repo name). 

Two possible solutions:

1. Internally work to be able to split on repo names with `.` so that resolution "just works"
2. Replace or escape offending characters in the repo name (for multi module projects only). So a repo at github.com/jitpack/jitpack.io with a module `Module` would be used with maven like 
```xml
<dependency> 
    <groupId>com.github.jitpack.jitpack_io</groupId> 
    <artifactId>Module</artifactId> 
    <version>Tag</version> 
</dependency>
```
The java specs on package naming say
> If the domain name contains a hyphen, or any other special character not allowed in an identifier (§3.8), convert it into an underscore.  

So underscore replacement seems a compliant solution.

**Comment by jitpack-io** [comment]
Hi,

Thanks for the suggestion! We'd like to support projects with `.` in the name though, as you noticed, there are issues using them in Maven compatible repositories.

When Gradle/Maven looks for a dependency it makes requests to JitPack with URL paths  `/com/github/user/repo/module/version/`. Basically, it translates `.`s in the dependency to `/`. JitPack uses this path to find the github repo to check out but if the repo contains dots then it's ambiguous.

Underscores do solve the issue to some extend but there could be edge cases when the repository contains an `_` itself. In that case we won't know whether `_` should be treated as `.` or not. Also ambiguous.

We could possibly support `~` as the replacement since it isn't an allowed symbol in repository names. Would that work for you?

**Comment by kag0** [comment]
That should work fine, thanks. Any guesstimate on when it might be available?

**Comment by jitpack-io** [comment]
Finished with the change. Planning to roll it out this weekend and will post an update here

**Comment by kag0** [comment]
@jitpack-io just checking in, is there an update yet?

**Comment by jitpack-io** [comment]
Yes, should be available already using `~`

**Comment by kag0** [comment]
The feature seems to be working fine for me now. Going to go ahead and close the issue.
