### ISSUE TITLE
Jitpack using JDK 6 now instead of 8

### ISSUE THREAD

**Issue by auras** [jitpack/jitpack.io#819]
Log https://jitpack.io/com/github/getsenic/lifx-sdk-android/0.6.1/build.log
Versus the old version which works https://jitpack.io/com/github/getsenic/lifx-sdk-android/0.6/build.log

**Comment by jitpack-io** [comment]
Hi,

This happened because there was an old targetSdkVersion in https://github.com/getsenic/lifx-sdk-android/blob/master/library/src/main/AndroidManifest.xml which is different from the one in build.gradle.
We'll need to fix this on our end. In the mean time you could update the AndroidManifest or use a jitpack.yml config file https://jitpack.io/docs/BUILDING/#java-version

**Comment by auras** [comment]
Yeah, that's not taken anymore into consideration by gradle.

Okay, thanks for the solution, it's working.

**Comment by jitpack-io** [comment]
Hi,

Fixed now to take into account targetSdkVersion in build.gradle

**Comment by auras** [comment]
Super, thanks
